// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: userrpc.proto

package server

import (
	"context"

	"greet/services/user/userrpc/internal/logic"
	"greet/services/user/userrpc/internal/svc"
	"greet/services/user/userrpc/userrpc"
)

type UserrpcServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserrpcServer
}

func NewUserrpcServer(svcCtx *svc.ServiceContext) *UserrpcServer {
	return &UserrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserrpcServer) Ping(ctx context.Context, in *userrpc.Request) (*userrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserrpcServer) GetUserByName(ctx context.Context, in *userrpc.GetUserByNameReq) (*userrpc.UserResp, error) {
	l := logic.NewGetUserByNameLogic(ctx, s.ctx)
	return l.GetUserByName(in)
}